- content/upcoming/cron-filesystem.md
This article demonstrates the use of the go9p package to create a simple cron service. The go9p package provides the machinery necessary to create 9p file systems in go which can be mounted on 3.x Linux kernels without installing any additional software. Once mounted any file access mechanism, i.e., shell, scripting language, compiled language, etc. can be used to interact with it.
> Added Cron as a file system article

- layouts/index.html
- layouts/partials/pagination.html
As introduced in Hugo 0.13.
Note: This uses the default config values:
paginate = 10
paginatepath = "page"
Could be adjusted to more or less items per page and a different url pattern (this gives /page/1 etc.).
> Add pagination to front page

- layouts-main/partials/header.html
- layouts/partials/header.html
Hugo has changed the default name of the Atom/RSS feed from rss.xml to index.xml.
See https://github.com/spf13/hugo/commit/596d67938668126d49cde7b00dc9f345f0f5032e
> Update static Atom/RSS feed urls to Hugo defaults

- content/gophercon2015-speakers-round-1.md
- layouts/partials/header.html
I wanted to create a new series for the gophercon posts this year.
Future posts should be in a subdirectory gophercon-2015/, but the first
announcement will have to stay where it is to avoid breaking inbound links.
I've included a hack which correctly capitalises the slug in the left nav
but cannot figure out how to do the same for the summary page that the
slug send you to.
Change-Id: I42c88fb681c82af0cbb9337b21de66798ae822e1
> Create "GopherCon 2015" series

- content/advent-2015/composable-pipelines-improvements.md
Very sorry about this, but it turns out I should have done even more thorough checking of those code examples in my pipelines post.
Have fixed them now, and also added a link pointing to a full working code example in a separate gist, since most of the code examples are heavily shortened down to get any kind of readability.
> Fix screwed up code examples, and add link to full code example in gist

- content/advent-2015/gopy.md
There are 2 articles published on the 16th
Shouldn't GoPy article be published on the 17th?
> Fix GoPy publication date

- content/advent-2016/tls-termination-bench.md
Two minor nits:
- letsencrypt should be Let's Encrypt
- SSL should be TLS (as per title)
- nginx should be Nginx (only one occurrence)
- vegeta should be Vegeta
- a awesome should be an awesome
/cc @fortytw2 @dgryski
> advent-2016: TLS termination nits

- content/advent-2016/go-timers.md
Article for Advent 2016 event about timers in Go. Timers include
time.Sleep, time.Timer and time.Ticker.
I hope it's okay to start new `advent-2016` directory. I marked the article as a draft for now, so it doesn't show on generated site.
ping @bketelsen @dgryski
> advent-2016: timers in Go

- content/advent-2016/context-logging.md
This post was originally posted in multiple parts and requests for
comments drawn from a couple of core authorities on the topic.  This
is a revision based on comments and feedback primarily from Peter
Bourgon.
For example, the feedback that storing 'common log objects' in context
might end up giving users the wrong idea, even though they are
log-scoped, was taken to heart: this code was already trimmed down
from my real code where I did that, so I could simplify the example to
just store the IDs and still serve the purpose of illustration.
Finally, the original plan to include a summary of three applications
of context in this piece with outlinks back to the full medium posts
were instead changed to include the introduction and the first piece,
based on feedback and engagement with the …
> advent-2016: add 'context' post

- content/advent-2016/go-timers.md
https://blog.gopheracademy.com/advent-2016/go-timers/ List near `noteclear` is broken.
> Another list fix.

- content/advent-2015/debugging-with-delve.md
Fixed links and mentioned progress on 32-bit support https://github.com/derekparker/delve/issues/20 instead of merged Windows PR.
> Fixes for debugging with Delve

- content/advent-2016/saga-go-dependency-management.md
Now the tool has been released, we should link to it so future readers can unambiguously find it.
This is a purely optional update.
cc @sdboyer
> Advent 2016: Update go dep mgmt saga timeline with tool url

- README.md
- config.toml
Sometime between 0.15 (the version running in production) and 0.31
(the current version), Hugo requires you to specify which theme you
are using, which in our case is "gaweb".
Not sure how best to test this, but without this patch hugo renders an
empty page, and with it, hugo renders the blog server.
> Support latest Hugo version

- content/advent-2017/custom-JSON-unmarshaler-for-GraphQL-client.md
This PR makes the following minor improvements:
- Wrap code blocks to fit into a smaller width, as displayed on the blog.gopheracademy.com website, especially at smaller window widths.
- Remove code tags from links, because blog.gopheracademy.com CSS makes it hard to tell they're links (they look just like non-link code fragments until you hover over them).
- Include domain in link to neelance/graphql-go project for consistency.
- Minor change in 25b3ea1 to improve consistency between example GraphQL query and its result.
/cc @bketelsen
> Custom JSON Unmarshaler: Improve formatting, presentation.

- content/advent-2017/go-wasm.md
The webassembly specifications website changed their layout.
Dezombify the dead links.
> advent-2017: update wasm post for new website layout

- content/advent-2017/go-1.10.md
The initial post / sum up of: https://tip.golang.org/doc/go1.10
> Add Go 1.10 changes blog post

- README.md
The new command line build drafts and future posts so contributors can preview series posts that haven't reached their post date yet.
I struggled with this and at least one other contributor reported being unable to build the site locally to preview an article, so I think it's good to have the instructions here.
> Improve instructions for hugo

- content/advent-2018/disk-datastores.md
Following #295 
There are couple broken links in "Golang and local datastores - fast and flexible data storage" post.
/cc @dgryski @gleicon
> Fix broken links for "Golang and local datastores" article

- content/advent-2018/llvm-ir-and-go.md
> llir: fix type in code example, use 21 instead of 32 in comment

- content/Como construir sitios web con HUGO.md
Hi there!. I made this article in the Spanish language, this is an article about how to build websites with HUGO.
> Spanish Article:Como construir sitios web con HUGO
