gopheracademy/gopheracademy-web

upcoming/go-and-ssh.md
I've read through it, though I'm not a great editor of my own work. Will get a friend to look through it soon. In the mean time, I thought I'd leave it here in case anyone else would like to proof-read :)
=> add post "go and ssh"

content/go-and-ssh.md
had my editor go over it - hopefully its not too much trouble to rebuild
=> more grammar and spelling fixes

upcoming/composable-pipelines-pattern.md
A new blog post, for possible inclusion on the Gopher Academy blog.
=> Suggested Blog post: Patterns for composable concurrent pipelines in Go

content/gophergala/data-mining.md
I wrote a blog post about the data mining aspect of my Gophergala entry.
I created a new folder content/gophergala for the blog post.
Since this is my first blog post and English isn't my first language, a review would be nice.
=>  Suggested Blog post: Gophergala entry - data mining

content/gophercon2015-speakers-round-1.md, content/gophercon2015-speakers-round-2.md, content/gophercon2015-speakers-round-3.md
Minor edits for the GopherCon 2015 speaker rounds.
:sunny: 
:dancer:
=> copyeditor strikes again

content/gophercon-2015/gophercon-ticket-sales.md
Change-Id: Ie66fc4bd62aab53368732ea19ac5ca44b3dd5f12
=> Added blog post about ticket sales

content/caddy-a-look-inside.md
Did I get the date and time right?
=> Article about Caddy

content/gophercon-2015/gophercon-lightning-talk-results.md
Blog post announcing the friday lightning talk sessions.
/cc @spf13 @erikstmartin @bketelsen @markbates
=> Added friday lightning talk results

content/advent-2015/afero-a-universal-filesystem-library.md
The Github diff tool isn't highlighting some of the edits (at least in my PR view), but I made some small corrections to the Afero post.
Cc: @spf13
=> Advent15: fix some Afero typos and punctuation

content/advent-2015/go-in-a-monorepo.md
Please review and provide critique!  Thanks again!
=> Advent 2015: Go in a Monorepo

content/advent-2015/libc-hooking-go-shared-libraries.md
For the December 2015 'Advent' series.
=> Add post: Hooking libc using Go shared libraries

content/advent-2015/reducing-boilerplate-with-go-generate.md
Sorry I just sent the PR now! I'm in my 5th city in just 2 weeks, so
everything has been a bit crazy with all the travelling.
I'll get somebody to review and make any amendmentes required first time
tomorrow morinng (EU time).
/cc @bketelsen
=> Post Advent 2015-12-10

content/advent-2015/go-in-a-yocto-project.md
This is the entry for next Sunday (December 12th).
I'll be happy to make any necessary corrections.
Thanks!
=> Go in a Yocto project

content/advent-2015/generate-free-tls-certs-with-lego.md
Advent 2015 series; scheduled for Dec. 15, 2015
=> 12/15 post: Generate and Use Free TLS Certificates with Lego

content/advent-2015/nats-high-performance-cloud-native-messaging-written-in-go.md
This is a draft blog post on NATS.io (gnatsd) for the GopherAcademy blog series this month, ready for peer review!
=> First Blog Post

content/advent-2015/nats-high-performance-cloud-native-messaging-written-in-go.md
Update the sample code to demonstrate more complex usage.
=> Update sample code

content/advent-2015/automi-stream-processing-over-go-channels.md
Found a correction to code sample.
=> Found correction to code sample.

content/advent-2015/composable-pipelines-improvements.md
Hi Guys, this is a suggestion for a follow-up on my composable pipelines post from february (https://blog.gopheracademy.com/composable-pipelines-pattern).
Best
// Samuel
=> Advent 2015 post suggestion: Composable pipelines improved

content/advent-2015/hydra-auth.md
Fixed 2 typos in the article about hydra
=> Fix typos in hydra-auth.md

content/advent-2015/building-static-linuxes.md
WIP while I wait for a short clip to upload to youtube. 
I haven't yet tested my asciinema embeds, will wrap up in a bit
Comments/criticism welcome!
=> Advent 2015 Series: Building Static Linuxes with Go

content/advent-2015/symmetric-api-testing-in-go.md
Here is my draft for the post scheduled for Dec. 26th.
=> Add draft of "Symmetric API Testing" (Advent 2015, Dec 26th)

content/advent-2015/etcd-distributed-key-value-store-with-grpc-http2.md
Reference:
https://docs.google.com/spreadsheets/d/1H0rj7TJo0t8GWyNdGwEc6bGcDj6UgJUN42JtAtbPMrk/edit#gid=0https://docs.google.com/spreadsheets/d/1H0rj7TJo0t8GWyNdGwEc6bGcDj6UgJUN42JtAtbPMrk/edit#gid=0
/cc @xiang90 @jonboulle @philips
Please review and let me know if you have any feedback.
Scheduled posting date is Tuesday, December 29th, 2015.
Thanks,
=> advent 2015: add etcd,grpc,http2 article

content/advent-2015/2d-games.md
It's kind of a survey of 2d gamedev options. Sorry for the lateness.
=> Advent 2015: 2D games in go

content/advent-2013/day-24-thank-you.md
Removes extraneous right bracket in the link.
=> Fix broken link in Advent 2013 Day 24.5

config-main.toml, config.toml, layouts-main/index.html, layouts-main/partials/header.html, layouts/partials/header.html, static/css/hc.css
I noticed the Roboto font wasn't loading, and I guess this is because the sites now use Let's Encrypt. I took the liberty to swap some other http links with https ones in the process. I hope you don't mind.
=> Fix unsafe resources (google fonts) and swap some direct http links to https

content/advent-2016/tls-termination-bench.md
A bit later than I hoped, with a little bit different topic (had some issues with my original topic, and not enough time...) 
Feedback greatly appreciated!
=> Advent 2016: Where to Terminate TLS?

content/advent-2016/peachpy.md
Minor edits to change `lets` to `let's`.
=> advent-2016: peachpy nits

content/advent_2016_NATS
Advent 2016 draft post - please verify embed to YouTube examples or Twitter render globally? If issues can resubmit with HTML link (not embedded link)..
=> Advent_2016_NATS

content/advent-2016/contributing-to-the-go-project.md
Here's my first draft of my blog for the Advent 2016 series.
Feedback is very welcome, feel free to ask questions and leave comments.
=> Advent 2016: Contributing to the Go project

content/advent-2016/database_sql.md
Post lists new features in the database/sql package in go1.8.
=> content/advent-2016: add database/sql feature post for 2016-12-09

content/advent-2016/some-tools-for-go-that-you-might-not-know-yet.md
First complete version. Comments welcome!
=> Advent 2016: Some Tools For Go That You Might Not Know Yet

content/advent-2016/pachyderm.md
Ok, here's my data post (what else would you expect from me, haha).  It's fairly long, but I tried to give a complete walkthrough of data pipelining via the Pachyderm Go client.  Let me know what questions, suggestions, etc. you have.  
btw, really enjoying reading the articles.  Great work on organizing this and really enjoying seeing the quality posts by all the authors.
=> Advent 2016: Data Pipelines and Versioning with the Pachyderm Go Client

content/advent-2016/saga-go-dependency-management.md
I believe this is basically in order, but comments are welcome. (This has 👍 from the pm committee)
=> Draft of go dep mgmt saga piece

content/advent-2016/goroutree.md
=> Goroutree post

content/advent-2016/sea-of-open-source.md
This is my post (cc @dgryski).
Please let me know if you think it can be improved.
Thank you.
=> The Sea of Open-Source

content/advent-2016/how-to-write-good-tests-for-solid-code.md
Here is a first draft.
I completed it jet lagged after a 25 hour trip... So every bit of feedback is welcome ;)
=> Writing good unit tests for SOLID Go

content/advent-2016/go-syntax-for-dsls.md
Latest version of my post. Thanks!
=> Abusing Go Syntax to create a Domain-Specific Language.

content/advent-2016/advanced-encoding-decoding.md
This is meant to be an alternate post in case someone doesn't get theirs ready, something unexpected comes up, or someone with multiple posts decides they don't want to write as many. You can see the spreadsheet here: https://docs.google.com/spreadsheets/d/1shwS1o-D2fPihea1NjKDH9KMheteRaJEqBjgsxkGmZA/edit#gid=0
I am creating the PR now so it is mostly ready (it needs a date) in case it is needed, and to get some review/feedback from everyone ahead of time.
=> DO NOT MERGE - Advent 2016: Advanced Encoding and Decoding Techniques in Go

content/advent-2016/gleam-distributed-map-reduce-for-golang.md
=> adding Gleam

content/advent-2016/implementing_gits-compression_algorithm_in_go.md
Greetings!
Here is the draft for my Advent series post, "Implementing Git's Compression Algorithm in Go".
I actually wasn't able to build this with Hugo yet, but I wanted to get the draft in to give everyone time to look it at the content as needed. I used `hugo new` to generate it, so I think we should be good.
=> Add "Implementing Git's Compression Algorithm in Go"

content/advent-2016/gobridge-beginners.md
Hi there. I wanted to contribute to making this post a little better by fixing a few tiny typos I spotted. Thanks!
Great post by the way!
Updates #221. /cc @Pisush @joncalhoun
=> Fix typos in gobridge-beginners.md post.

content/advent-2016/machine-learning-google-prediction-api.md
Initial draft of "A little bit of Machine Learning: Playing with Google's Prediction API"
=> A little bit of Machine Learning: Playing with Google's Prediction API

content/gophercon-2017/writing-a-successful-gophercon-proposal.md
=> rearanges sections of gophercon-2017 writing proposal

content/advent-2017/cfr.md
... I suspect there was an accidental omission via copypasta. ;)
=> CFR links to 2016 too

content/advent-2017/gopherjs-grpc-web.md
This is the first draft of my post about my GopherJS gRPC-Web bindings. I'm open to feedback at this stage but will be making small changes until I'm completely pleased with it.
=> Add GopherJS gRPC-Web bindings post (2nd of December)

content/advent-2017/make.md
Two commits since I needed the first one to view and test how the post looked locally.
=> Add blog post about Make (Dec 2nd)

content/advent-2017/managing-dependencies-forks-and-code-patches-with-dep.md
Add draft of "Managing Dependencies with Dep"
https://docs.google.com/spreadsheets/d/1HjldwvQzJFvaVf-2Em1O-s--soXZzqyXmwkZkrw7nhw/edit#gid=0
=> Add Managing Dependencies with Dep post (Dec 6)

content/advent-2017/custom-JSON-unmarshaler-for-GraphQL-client.md
I had a specific story I wanted to tell. It ended up being larger than I expected. But I think/hope it's good enough despite being a large post.
This is the current state. Content is 100% complete. What's left is proof-reading and copy-editing. I will be doing that myself soon, and I welcome any additional feedback. Thanks!
P.S. I know it's late for a post scheduled for tomorrow. Sorry! It took longer than I thought.
=> Advent 2017: Custom JSON unmarshaler for a GraphQL client (Dec 8)

content/advent-2017/property-based-testing.md
There's about 1500 words more to go.
=> Complete draft for property based testing (Dec 9) - invitation to copy-edit

content/advent-2017/custom-JSON-unmarshaler-for-GraphQL-client.md
These are additional minor improvements that I found.
They are not time-sensitive.
=> Custom JSON Unmarshaler: Apply long tail tweaks.

content/advent-2017/go-grpc-beyond-basics.md
This is my first draft of my post scheduled for 13 December - **gRPC Go: Beyond the basics**.
I'm open to any corrections on errors and wrong wording & suggestions.
Thanks for the opportunity.
=> Advent 2017 - gRPC Go : Beyond the basics (13 Dec)

content/advent-2017/kubernetes-ready-service.md
Hello, there is a draft of the article for Dec, 14.
**I need help with English**, so it would be nice if someone can help to fix my mistakes and grammar. 
Thank you very much!
=> Dec, 14. Write a Kubernetes-ready service from zero step-by-step

content/advent-2017/unsafe-pointer-and-system-calls.md
Feedback welcome.  This ended up a bit longer than I expected due to all of the warnings about various misuses of `unsafe`, but I feel pretty happy with it overall.
This post is for December 15.
=> Advent 2017: unsafe.Pointer and system calls (Dec 15th)

content/advent-2017/kubernetes-ready-service.md
Post-processing :)
Fix logical mistakes and add a few notes based on comments and questions.
=> Advent 2017. Kubernetes-ready service. Fixes and notes.

content/advent-2017/unsafe-pointer-and-system-calls.md
=> Advent 2017: fix code example in unsafe post

content/advent-2017/go-wasm.md
This CL adds a first draft for the go-wasm post of 2017/12/17.
=> content/advent-2017: add go-wasm (Dec 17th)

content/advent-2017/accessing-smbios-information-with-go.md
Please feel free to post this as an alternate if needed, or otherwise, I'd be happy to contribute it to the Gopher Academy blog in January, or just move it to my Medium account.
Edit: post is now complete. Please provide feedback!
/cc @dgryski per our conversation on Slack.
=> Advent 2017: Accessing SMBIOS information with Go (alternate post)

content/advent-2017/osquery-sdk.md
Looking forward to your reviews. 
// cc @zwass @marpaia
=> add blog post on osquery sdk (Dec 21)

content/advent-2017/run-group.md
=> Advent 2017: Managing goroutine lifecycles with run.Group (24 Dec)

content/advent-2017/mage.md
Discusses the what Mage is and how it works.
=> Article about Mage

content/advent-2017/using-go-templates.md
The article for Dec 27th.
Maybe there're some mistakes as I'm not native speaker and I didn't have a free time for copyediting. Feedback is appreciated.
=> Advent 2017: Using Go Templates (Dec 27th)

content/advent-2017/tensorflow-and-go.md
Following a chat with @asimshankar from the TensorFlow team, here's a small correction that the Go API does allow training. Also some capitalization fixes.
=> Dec 28 Update: TensorFlow and Go

content/advent-2018/split-data-with-cdc.md
So, here's the first version of my post for the Advent 2018. Please let me know if there are any errors (typos or otherwise)! :)
=> Advent 2018: Splitting Data With CDC

content/advent-2018/postmortem-debugging-delve.md
The draft of my "Postmortem debugging Go services with Delve" tutorial/guide, for 2nd of December. The feedback and comments are very appreciated.
=> Advent 2018: Postmortem debugging Go services with Delve

content/advent-2018/mage-best-practices.md
=> add mage article

content/advent-2018/observability-in-the-kitchen.md
Here is my blog submission for Advent 2018.
=> Advent2018 - Observability in the Kitchen

.gitignore, content/advent-2018/gpython.md
Here is the first draft of an article on gpython for the gopher academy advent.
Any criticisms gratefully accepted :-)
=> Advent 2018-12-12: Gpython

content/advent-2018/go-arrow.md
=> Hotfixes for Apache Arrow post

content/advent-2018/go-arrow.md
=> More arrow hotfixes

content/advent-2018/llvm-ir-and-go.md
The fix of the link in the previous PR was not correct.
Sorry for the noise. This should be the final PR.
Thanks a lot and happy Advent!
Cheers,
Robin
=> llir: fix wiki link (take 2)

content/advent-2018/exporting.md
arbitrarily set date to 12-17, feel free to change that, let me know if you want edits/changes.
=> advent post

content/testcontainers-go.md
I have spoke with Brian via email and here we are.
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
=> Article about testcontainers

content/reactive-planning-go.md
Hello! I wrote this article because I got excited by this pattern I used
at work. I received a good response by the community and I have also
exposed it during a local conference in Turin called FullStackConf.
I would like to get it published on Gopher Academy as well if possible.
Thanks a lot
Signed-off-by: Gianluca Arbezzano <gianarb92@gmail.com>
=> Reactive planning and reconciliation in Go

content/advent-2019/safe-use-of-unsafe-pointer.md
Review is welcome and appreciated, thanks! This is for December 5th.
=> advent-2019: Safe use of unsafe.Pointer blog

content/advent-2019/benchmark-magic.md
This is a draft, it should be usable, but it wouldn't hurt to
add more links, I guess?
=> draft of benchmarking post for 2019 gopheracademy advent calendar

content/advent-2019/benchmark-magic.md
forgot to include author identification in post, sorry
=> identify author of post

content/advent-2019/advent-of-code.md
Can someone verify that my image linking is done correctly? This hugo setup is slightly different from what I'm accustomed to.
=> advent-2019: Dec 10 - Test Driven Advent of Code

content/advent-2019/building-a-microservices-network.md
Set the ?sanitize=true query string to ensure there are no scripts.
raw.githubusercontent.com doesn't send the correct content type headers otherwise.
=> advent-2019: Dec 8 Fix broken SVG image

content/advent-2019/control-packetflow-tcp-nodelay.md
My advent blog post about using TCP_NODELAY in Go. This is for December 11th.
Feedback is always appreciated! :-)
=> advent-2019: Dec 11 - Control packet flow with TCP_NODELAY in Go

content/advent-2019/writing-go-user-interfaces-with-vugu.md
Here is my submission for the Advent 2019 article on Vugu.
The article walks through what Vugu is and the background on the utility it is trying to provide in helping Go become a viable client-side language; and includes various code snippets and link to a sample app I made for this article: The Mathematics of Santa.
@bketelsen Sorry about how last-minute this is - I meant to get this over to you earlier, but holidays are crazy and it took a bit to get this all put together and ready.   Hopefully this can still be made to happen by the 25th.
I'll look out for any updates on this PR and I'm usually available on the Gopher slack.
=> Vugu article, Advent 2019
